# Generated by Django 3.2 on 2021-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approval',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Disapproved')], default=1),
        ),
    ]
