# Generated by Django 3.2 on 2021-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_comment_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='exprDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
