# Generated by Django 3.2 on 2021-04-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_usersite'),
        ('store', '0004_auto_20210419_2117'),
    ]

    operations = [
    ]
