# Generated by Django 3.2 on 2021-04-24 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_delete_usersite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='adress',
        ),
        migrations.AddField(
            model_name='product',
            name='onDiscount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardAlias', models.CharField(blank=True, max_length=100, null=True)),
                ('cardName', models.CharField(max_length=100, null=True)),
                ('cardNumber', models.CharField(blank=True, max_length=19, null=True)),
                ('exprDate', models.DateField()),
                ('exprMon', models.CharField(max_length=100)),
                ('exprDay', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('customerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
