# Generated by Django 3.2 on 2021-05-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210424_2203'),
        ('store', '0007_rename_adress_shippingadress_address'),
    ]

    operations = [
    ]
