# Generated by Django 3.2 on 2021-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210504_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
