# Generated by Django 3.2 on 2021-05-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # dependencies = [
    #     ('store', '0007_auto_20210424_2203'),
    # ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
