# Generated by Django 3.2 on 2021-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210505_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='cardName',
            new_name='cardOwnerName',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='customerID',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='cardAlias',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='exprDay',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='exprMon',
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='exprDate',
            field=models.CharField(max_length=100),
        ),
    ]
