# Generated by Django 3.2 on 2021-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_iscomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isComplete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
