# Generated by Django 3.2 on 2021-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210505_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='cardAlias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
