# Generated by Django 3.2 on 2021-06-01 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210526_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cardNumber',
            field=models.CharField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='exprDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rating',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
