# Generated by Django 3.2 on 2021-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_request',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
