# Generated by Django 3.2 on 2021-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_orderitem_refund_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
