# Generated by Django 3.2 on 2021-04-29 14:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('my_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
