# Generated by Django 3.2 on 2021-05-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
