# Generated by Django 3.2 on 2021-05-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_iscomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='warrantry',
            new_name='warranty',
        ),
    ]
