# Generated by Django 3.2 on 2021-05-25 11:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_shippingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=100, null=True)),
                ('cardAlias', models.CharField(blank=True, max_length=100, null=True)),
                ('cardNumber', models.CharField(blank=True, max_length=19, null=True)),
                ('exprDate', models.CharField(blank=True, max_length=100, null=True)),
                ('customerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
