# Generated by Django 3.2 on 2021-05-25 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210525_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_score',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rating_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
