# Generated by Django 3.2 on 2021-05-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210526_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_ratings', to='api.orderitem'),
        ),
    ]
