# Generated by Django 3.2 on 2021-05-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_orderitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='api.product'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
