# Generated by Django 3.2.3 on 2021-06-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210601_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Intransit'), (3, 'Delivered')], default=1),
        ),
    ]
