# Generated by Django 3.2.3 on 2021-06-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='onDiscount',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Disapproved')], default=1)),
                ('onDiscount', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_order_item', to='api.orderitem')),
            ],
        ),
    ]
